Fix mention
OpenTreeHole/treehole_next pull request #32
Opened 2022-09-21 09:24 UTC by JingYiJun

2022-09-21 10:19 UTC, hasbai requested changes
感觉还是用 gorm 的功能自动维护就好，手动维护会对现有业务造成侵入，也容易出 bug

2022-09-21 10:19 UTC, hasbai commented on apis/floor/apis.go
> +		err = floor.SetMention(DB, true)
就是说把这个写到AfterSave里面，不然没个涉及修改content的都要写这么一句

2022-09-21 10:19 UTC, hasbai commented on models/floor.go
> +func (floor *Floor) SetMention(tx *gorm.DB, clear bool) error {
这里面没FindMention啊

2022-09-21 10:19 UTC, hasbai commented on models/floor.go
> +	builder.WriteString("")
这里面没考虑到sqlite

2022-09-21 12:19 UTC, JingYiJun commented on apis/floor/apis.go
> +	for i := range floor.Mention {
写进去了

2022-09-21 12:20 UTC, JingYiJun commented on apis/floor/apis.go
> +		err = floor.SetMention(DB, true)
写到afterUpdate里面了

2022-09-21 12:21 UTC, JingYiJun commented on apis/floor/apis.go
> +		err = floor.SetMention(DB, true)
但是其实有问题，因为如果modifyfloor的时候不修改content，就不会涉及到findmention和setmention的行为，但是afterupdate和aftersave默认会执行，会出问题

2022-09-21 12:22 UTC, JingYiJun commented on models/floor.go
> +	builder.WriteString("")
已修改

2022-09-21 13:03 UTC, JingYiJun commented on models/floor.go
> +func (floor *Floor) SetMention(tx *gorm.DB, clear bool) error {
写到SetMention里面了

2022-09-21 15:15 UTC, hasbai requested changes

2022-09-21 15:15 UTC, hasbai commented on models/floor.go
>  func (floor *Floor) SetMention(tx *gorm.DB, clear bool) error {
我是说这里没有必要手动的去写这么多你直接用gorm的功能让他自己去处理就好了。你可以去统计一下那个日志，对吧？你看看这个到底是他的使用的是不是很频繁对吧？我估计来看的话就是修改帖子的这个需求使用了其实不是很多而且呃，我也是想要，就是说把之前手动写的处理TAG的那一大段给替换掉了，因为这个因为这个确实会增加很多BUG，然后难以维护这样子，所以我感觉最好这边不要自己去写了

2022-09-21 15:15 UTC, hasbai commented on models/report.go
> +func (reports *Reports) Preprocess(c *fiber.Ctx) error {
直接去用下标访问就可以了，不要用指针去传递数组

2022-09-21 15:15 UTC, hasbai commented on apis/report/apis.go
> -	result := DB.Preload("Floor.Mention").
你这个还是没有消除重复代码呀。那一共有3个那个PRELOAD的地方，但你这个只做了2个，那我的意思是，你就可以写一个类似于PRELOAD的函数吗？然后接受一个 DB，然后在里面preload那 2个，然后再把它吐出来，

2022-09-21 15:17 UTC, hasbai commented on apis/floor/apis.go
> +		err = floor.SetMention(DB, true)
你说的有道理，那最好还是把它放在修改content的那个部分的里面，还有create里面

2022-09-23 05:15 UTC, JingYiJun commented on models/floor.go
> +func (floors *Floors) Preprocess(c *fiber.Ctx) error {
已修改

2022-09-23 05:26 UTC, JingYiJun commented on models/floor.go
>  func (floor *Floor) SetMention(tx *gorm.DB, clear bool) error {
这里手动处理是因为gorm的功能自动处理达不到需求，你更新mention的时候他会默认有floor的插入操作，因为gorm也不知道找到的mention是数据库里已经有的还是新的，那他默认有一个Create操作，就自动调用AfterCreate了。其实不是save的问题，是这个gorm他确实功能有限。

2022-09-23 05:26 UTC, JingYiJun commented on apis/report/apis.go
> -	result := DB.Preload("Floor.Mention").
已经处理

2022-09-23 05:27 UTC, JingYiJun commented on apis/floor/apis.go
> +		err = floor.SetMention(DB, true)
Create的我就放到AfterCreate里面了，因为无论如何都会调用AfterCreate

2022-09-23 05:46 UTC, JingYiJun commented
> 感觉还是用 gorm 的功能自动维护就好，手动维护会对现有业务造成侵入，也容易出 bug

gorm 的功能自动维护反而会出现Bug，因为gorm的文档写的不完全，也不知道到底会出现什么样的操作。。。另外有些重复的修改，merge的时候可以压缩到一个commit里面吗QAQ

2022-09-23 08:31 UTC, hasbai approved these changes

2022-09-23 08:31 UTC, merged