Fix report null
OpenTreeHole/treehole_next pull request #33
Opened 2022-09-21 13:11 UTC by ryanhe312

2022-09-21 15:22 UTC, hasbai requested changes

2022-09-21 15:22 UTC, hasbai commented on models/floor.go
> +	println(3)
这个三是什么意思？是不是忘记删掉了

2022-09-21 15:22 UTC, hasbai commented on models/schemas.go
> +	Sort    string `query:"sort" default:"desc" validate:"oneof=asc desc"` // Sort order
你不要改那个基础的字段呀。应该是重写那个REPORT里面的query的方法你看一下能不能重写。

2022-09-21 15:48 UTC, ryanhe312 commented on models/floor.go
> +	println(3)
确实

2022-09-21 15:50 UTC, ryanhe312 commented on models/schemas.go
> +	Sort    string `query:"sort" default:"desc" validate:"oneof=asc desc"` // Sort order
ListReports里面没办法判断前端给的是asc还是desc，那要不就直接写死成desc好了

2022-09-22 02:27 UTC, hasbai commented on models/schemas.go
> +	Sort    string `query:"sort" default:"desc" validate:"oneof=asc desc"` // Sort order
可以重写listmodel里面的sort字段，看看这样能不能改掉默认值

2022-09-22 02:30 UTC, hasbai commented on apis/report/apis.go
>  	query.OrderBy = "`report`.`" + query.OrderBy + "`"
看看这行删掉会不会有bug，尽量不要把字段格式的修改放到api层里面

2022-09-22 14:35 UTC, ryanhe312 commented on apis/report/apis.go
>  	query.OrderBy = "`report`.`" + query.OrderBy + "`"
有bug会返回
`22:34:15 | 500 |     1ms |       127.0.0.1 | GET     | /api/reports                               | ambiguous column name: id`

2022-09-22 14:45 UTC, ryanhe312 commented on models/schemas.go
> +	Sort    string `query:"sort" default:"desc" validate:"oneof=asc desc"` // Sort order
不能，这样会有两个Sort，而且导致model.Query里面的字段得不到更新，一直是asc

2022-09-22 14:47 UTC, ryanhe312 commented on models/schemas.go
> +	Sort    string `query:"sort" default:"desc" validate:"oneof=asc desc"` // Sort order
这样修改不会写死，只会更改默认值
```
func ListReports(c *fiber.Ctx) error {
	// validate query
	var query ListModel
	query.Sort = "desc"
	err := ValidateQuery(c, &query)
	if err != nil {
		return err
	}
	query.OrderBy = "`report`.`" + query.OrderBy + "`"
```

2022-09-22 14:50 UTC, ryanhe312 commented on apis/report/apis.go
>  	query.OrderBy = "`report`.`" + query.OrderBy + "`"
因为query解析已经写死了，所以这也是没办法

2022-09-23 09:10 UTC, hasbai approved these changes
可以看一下我的那个 commit， 其实是可以重写的，因为方法调用的同名字段会优先使用外层的，也就是重写上去的字段，所以说它的默认值是可以直接在模型层面去设置。
你可能没有重写那个 base query 的方法，因为如果我不重写的话，它会调用的是内层 query 的方法，这样你外层重写的字段就用不到。

2022-09-23 09:11 UTC, merged